### PR TITLE
Revert "Create org webhook for jenkins (#20)"

### PR DESCRIPTION
**Pull request by joakime**
This reverts commit 654f8f5669eadf57fec3e5640f3cd148998bcc28.

It is not appropriate to have Jenkins Webhooks at org level.
This should be reverted.

### CODE REVIEW

**Comment by netomi** [comment]
I may have suggested something that is not inline with your CI configuration at webtide, however it is common practice for many eclipse projects to enable a webhook on organization level to trigger builds on jenkins. My understanding is that the jenkins instance only receives information about PRs or pushes from repos and starts a build if a corresponding job is available that has GitHub hook trigger for GITScm polling enabled. If events are received for repos where no job is configured, nothing will happen.

Now, if you prefer to have an explicit webhook defined on repo level for repos which have such a job on jenkins, its perfectly fine for me ofc.

**Comment by olamy** [comment]
@joakime Why?

**Comment by joakime** [comment]
We don't want to jeopardize jenkins.webtide.net use for the important repos by having repos that never use it (and having github flag it as a problematic webhook server).

A few or our repos will use jenkins.webtide.net, not 100% of them.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live

**Comment by fredg02** [comment]
> We don't want to jeopardize jenkins.webtide.net use for the important repos by having repos that never use it (and having github flag it as a problematic webhook server).

Out of curiosity: why/how would GitHub flag jenkins.webtide.net as a "problemativ webhook server"? With a webhook on the org level, jenkins.webtide.net would receive all webhook events just fine, but only start a build for repositories that have a build job set up. jenkins.webtide.net won't return a 404 or similar error code to GitHub for repos that have no build job, so GitHub has no way of telling that a webhook is sent that does not kick off a build (and they mostly likely don't care).

**Pull request merged**
