### PR TITLE
Update jetty.jsonnet

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
move the jetty.website repo so we can move the new one in

### CODE REVIEW

**Comment by netomi** [comment]
Is there any specific reason to not delete this repo right away as it is empty atm?

Otherwise, you can merge yourself by adding /otterdog merge as comment

**Comment by jmcc0nn3ll** [comment]
deleting it would be fine, I just need to transfer the other repo into the jetty org and then fix up an otterdog reference for it

**Comment by netomi** [comment]
or add a new remote and push everything to the existing jetty/jetty.website repo? Then you would not need to go through the hassle of transfering the repo unless it is required ofc.

**Comment by jmcc0nn3ll** [comment]
> or add a new remote and push everything to the existing jetty/jetty.website repo? Then you would not need to go through the hassle of transfering the repo unless it is required ofc.

It has existing Issues that would be good to preserve.

**Comment by netomi** [comment]
ah I see then it makes sense to transfer it.

**Review by netomi — APPROVED** [review]

**Review by netomi — APPROVED** [review]
its easier to delete it now, and after the transfer to reimport with the current settings.
You can then adjust the settings afterwards as needed.

**Comment by jmcc0nn3ll** [comment]
@netomi It looks like I do not have rights to transfer the repository to the jetty organization.

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14595

Any idea how I can get this done?

**Comment by netomi** [comment]
So the IP checks seems to have been resolved successfully. You need to create a ticket in the HelpDesk for the transfer.
Usually you have to invite a user (eclipsewebmaster) to the webtide org to do the transfer.

**Comment by jmcc0nn3ll** [comment]
That would be a non-starter. I'll look closer into transferring the repo contents.

**Comment by netomi** [comment]
thats the typical process and the user can be removed after the transfer again. If you absolutely not want that it might also be possible to temporarily grant you owner rights for the jetty org to do the transfer yourself, but best check in the HelpDesk as this is a bit out of my league.

**Pull request merged**
