### PR TITLE
Add jetty.setuid repository.

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
new repository target for jetty.toolchain/jetty-setuid module

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by jmcc0nn3ll** [comment]
Not sure I follow, could you point me at it?

**Comment by netomi** [comment]
In order to support your use-case for bypassing branch protection rules by some users, we manually configured a repository ruleset:

https://github.com/jetty/.eclipsefdn/blob/main/otterdog/jetty.jsonnet#L141

which was not yet supported by the self-service tool, but I managed to complete support now, and you will now also be able to configure that via the self-service. Just that you are aware of it.

**Comment by olamy** [comment]
@netomi do we need to add webhook for our Jenkins in every single git repo creation or could it be automatic?

**Comment by netomi** [comment]
No, I think a single org webhook is sufficient:

https://github.com/eclipse-cdt/.eclipsefdn/blob/main/otterdog/eclipse-cdt.jsonnet#L28

**Comment by netomi** [comment]
Although I am not sure how you plan to do CI. If you use ci.eclipse.org/jetty the org webhook is normally enough.
If you have your own jenkins and need a webhook for each repo individually, we can setup some defaults that for each repo an automatic webhook will be generated, but I would need to know how you setup is then I can make a PR.

**Comment by olamy** [comment]
we use our own Jenkins.
webhook already setup for few project https://github.com/jetty/.eclipsefdn/blob/b5e634bd592fb462224fb2815f04a0f5d07cac6a/otterdog/jetty.jsonnet#L144

would be easier at org level. do you need a PR for that?
Thanks!

**Comment by netomi** [comment]
Created https://github.com/jetty/.eclipsefdn/pull/20 to create an org webhook.

**Pull request merged**
